<a href="https://colab.research.google.com/github/prakhar00007/genai-notebooks/blob/main/embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## One Hot Encoding

In [1]:
corpus=['I love NLP','I teach Gen AI',"I am working on Euron"]

In [7]:
corpus= [text.lower() for text in corpus]


In [8]:
corpus

['i love nlp', 'i teach gen ai', 'i am working on euron']

In [24]:
unique_words=list(set(" ".join(corpus).split()))

In [25]:
unique_words


['love', 'working', 'ai', 'nlp', 'gen', 'euron', 'am', 'i', 'on', 'teach']

In [26]:
enumerate(unique_words)

In [29]:
enu=iter(enumerate(unique_words))

In [32]:
next(enu)

(2, 'ai')

In [34]:
for i in enumerate(unique_words):
  print(i)

(0, 'love')
(1, 'working')
(2, 'ai')
(3, 'nlp')
(4, 'gen')
(5, 'euron')
(6, 'am')
(7, 'i')
(8, 'on')
(9, 'teach')


In [38]:
for i, word in enumerate(unique_words):
    print(f"{word}: {i}")


love: 0
working: 1
ai: 2
nlp: 3
gen: 4
euron: 5
am: 6
i: 7
on: 8
teach: 9


In [39]:
word_to_index = {word: i for i, word in enumerate(unique_words)}


In [40]:
word_to_index

{'love': 0,
 'working': 1,
 'ai': 2,
 'nlp': 3,
 'gen': 4,
 'euron': 5,
 'am': 6,
 'i': 7,
 'on': 8,
 'teach': 9}

In [41]:
corpus

['i love nlp', 'i teach gen ai', 'i am working on euron']

In [42]:
one_hot_encoder=[]
for sentence in corpus:
  print(sentence)
  sentence_vector=[]

i love nlp
i teach gen ai
i am working on euron


In [55]:
one_hot_vecotor = []
for sentence in corpus:
    print(sentence)
    sentence_vector = []
    for word in sentence.split():
        vector = [0] * len(unique_words)
        print(vector)
        vector[word_to_index[word]] = 1
        print('word to index',word_to_index[word])
        print(vector[word_to_index[word]])
        print('sentece vector befor appending',sentence_vector)
        sentence_vector.append(vector)
        print('sentence vector after appending',sentence_vector)

    one_hot_vecotor.append(sentence_vector)
    print('-----------')


i love nlp
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
word to index 7
1
sentece vector befor appending []
sentence vector after appending [[0, 0, 0, 0, 0, 0, 0, 1, 0, 0]]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
word to index 0
1
sentece vector befor appending [[0, 0, 0, 0, 0, 0, 0, 1, 0, 0]]
sentence vector after appending [[0, 0, 0, 0, 0, 0, 0, 1, 0, 0], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
word to index 3
1
sentece vector befor appending [[0, 0, 0, 0, 0, 0, 0, 1, 0, 0], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
sentence vector after appending [[0, 0, 0, 0, 0, 0, 0, 1, 0, 0], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0]]
-----------
i teach gen ai
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
word to index 7
1
sentece vector befor appending []
sentence vector after appending [[0, 0, 0, 0, 0, 0, 0, 1, 0, 0]]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
word to index 9
1
sentece vector befor appending [[0, 0, 0, 0, 0, 0, 0, 1, 0, 0]]
sentence vector after appending [[0, 0, 0, 0, 0, 0, 0, 1, 0, 0], [0, 

In [52]:
one_hot_vecotor

[[[0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
  [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 1, 0, 0, 0, 0, 0, 0]],
 [[0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
  [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
  [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]],
 [[0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
  [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
  [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
  [0, 0, 0, 0, 0, 1, 0, 0, 0, 0]]]

##Bag of Words (BOW)

In [2]:
 corpus=['i love nlp','i teach gen ai','i am working with euron']

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
vectorizer=CountVectorizer()

In [7]:
X=vectorizer.fit_transform(corpus)

In [8]:
X.toarray()

array([[0, 0, 0, 0, 1, 1, 0, 0, 0],
       [1, 0, 0, 1, 0, 0, 1, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 1, 1]])

## TF-IDF

In [9]:
corpus=['i love nlp','i teach gen ai','i am working with euron']

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [11]:
vector_tf_idf= TfidfVectorizer()

In [15]:
X= vector_tf_idf.fit_transform(corpus)

In [18]:
X.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.70710678,
        0.70710678, 0.        , 0.        , 0.        ],
       [0.57735027, 0.        , 0.        , 0.57735027, 0.        ,
        0.        , 0.57735027, 0.        , 0.        ],
       [0.        , 0.5       , 0.5       , 0.        , 0.        ,
        0.        , 0.        , 0.5       , 0.5       ]])

In [26]:
corpus

['i love nlp', 'i teach gen ai', 'i am working with euron']

In [33]:
len(list(set(" ".join(corpus).split())))

10

In [34]:
corpus_new=['pappu nach nahi sakta','pappu loves dancing', 'pappu stops dancing']

In [35]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [36]:
vector_tf_idf= TfidfVectorizer()

In [38]:
X=vector_tf_idf.fit_transform(corpus_new)


In [41]:
X.toarray()

array([[0.        , 0.        , 0.54645401, 0.54645401, 0.32274454,
        0.54645401, 0.        ],
       [0.54783215, 0.72033345, 0.        , 0.        , 0.42544054,
        0.        , 0.        ],
       [0.54783215, 0.        , 0.        , 0.        , 0.42544054,
        0.        , 0.72033345]])

In [42]:
from sklearn.feature_extraction.text import CountVectorizer

In [43]:
vectorizer= CountVectorizer()

In [44]:
x= vectorizer.fit_transform(corpus_new)

In [45]:
x.toarray()

array([[0, 0, 1, 1, 1, 1, 0],
       [1, 1, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 0, 1]])

## Word2Vec

In [3]:
!pip install gensim

In [4]:
import nltk
import string
import matplotlib.pyplot as plt
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import numpy as np
import re

In [5]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [6]:
corpus=[
    'my name is Sudhanshu kumar',
    'i use to Teach all data stack along with ops and cloud!',
    'fadll dlkjfkl #@*234 lkjdf #34533',
    'nlp is very Amazing',
    'We are trying to learn word2vec',
    'we will try to build two models for word2vec - cbow and skipgram',
    'we will also working on cleaning the data which is going to have some noisy data. it"s basically part of pre-processing',
    'nlp is a part of AI',
    'word2vec is better than one hot encoding, tf-idf,bags of words'

]

In [7]:
cleaned_corpus = [re.sub(r'\d+', '', sentence.lower()) for sentence in corpus]


In [8]:
cleaned_corpus

['my name is sudhanshu kumar',
 'i use to teach all data stack along with ops and cloud!',
 'fadll dlkjfkl #@* lkjdf #',
 'nlp is very amazing',
 'we are trying to learn wordvec',
 'we will try to build two models for wordvec - cbow and skipgram',
 'we will also working on cleaning the data which is going to have some noisy data. it"s basically part of pre-processing',
 'nlp is a part of ai',
 'wordvec is better than one hot encoding, tf-idf,bags of words']

In [9]:
cleaned_corpus = [''.join(ch for ch in sentence if ch not in string.punctuation) for sentence in cleaned_corpus]


In [10]:
cleaned_corpus



['my name is sudhanshu kumar',
 'i use to teach all data stack along with ops and cloud',
 'fadll dlkjfkl  lkjdf ',
 'nlp is very amazing',
 'we are trying to learn wordvec',
 'we will try to build two models for wordvec  cbow and skipgram',
 'we will also working on cleaning the data which is going to have some noisy data its basically part of preprocessing',
 'nlp is a part of ai',
 'wordvec is better than one hot encoding tfidfbags of words']

In [11]:
filtered_corpus = [
    ' '.join([word for word in sentence.split() if word not in stopwords.words('english')])
    for sentence in cleaned_corpus
]

print(filtered_corpus)

['name sudhanshu kumar', 'use teach data stack along ops cloud', 'fadll dlkjfkl lkjdf', 'nlp amazing', 'trying learn wordvec', 'try build two models wordvec cbow skipgram', 'also working cleaning data going noisy data basically part preprocessing', 'nlp part ai', 'wordvec better one hot encoding tfidfbags words']


In [12]:
filtered_corpus

['name sudhanshu kumar',
 'use teach data stack along ops cloud',
 'fadll dlkjfkl lkjdf',
 'nlp amazing',
 'trying learn wordvec',
 'try build two models wordvec cbow skipgram',
 'also working cleaning data going noisy data basically part preprocessing',
 'nlp part ai',
 'wordvec better one hot encoding tfidfbags words']

In [13]:
tokenized_corpus = [sentence.split() for sentence in filtered_corpus]
tokenized_corpus


[['name', 'sudhanshu', 'kumar'],
 ['use', 'teach', 'data', 'stack', 'along', 'ops', 'cloud'],
 ['fadll', 'dlkjfkl', 'lkjdf'],
 ['nlp', 'amazing'],
 ['trying', 'learn', 'wordvec'],
 ['try', 'build', 'two', 'models', 'wordvec', 'cbow', 'skipgram'],
 ['also',
  'working',
  'cleaning',
  'data',
  'going',
  'noisy',
  'data',
  'basically',
  'part',
  'preprocessing'],
 ['nlp', 'part', 'ai'],
 ['wordvec', 'better', 'one', 'hot', 'encoding', 'tfidfbags', 'words']]

In [16]:
word2vec_cbow=Word2Vec(sentences=tokenized_corpus,vector_size=100,window=5,min_count=1,sg=0)

In [17]:
word2vec_skipgram=Word2Vec(sentences=tokenized_corpus,vector_size=100,window=5,min_count=1,sg=1)